Feature/clean folder
djmary-k/App_assistant pull request #6
Opened 2023-09-11 20:25 UTC by TetianaShevch

'Clean folder' asks user about folder should be cleaned and destination folder for sorted files. 
Files are sorted in accordance with their extensions. If the extension is unknown or empty files are transferred in folder with name 'Others'. 
The names of files should be normalized. The archives should be unpacked in the folder with name equal the name of archive in the folder 'Archives'. 
After running of application the initial folder should be empty.

2023-09-11 20:46 UTC, djmary-k approved these changes

2023-09-11 20:52 UTC, djmary-k requested changes
В main.py зробіть, будь ласка, функцію def main() i перенесіть туди код зі строки 6 по 28, а в 
if __name__ =="__main__":  допишіть main()

2023-09-11 20:57 UTC, djmary-k requested changes
Ви відправили цей пул реквест до main гілки. Змініть гілку на dev.

2023-09-12 04:15 UTC, djmary-k requested changes
Добрий ранок Тетяно! Ви клонувались від неправильної гілки, ви зробили клон він main, а потрібно було клонуватись від dev. Тепер коли ви зробили пул реквест, виник конфлікт, ваш файл main хоче замінти  мій файл main. Щоб корректно залити ваші файли в правильну папку я рекомендую вам зробити іще одну гілку, тільки клонуватися від dev гілки, потім скопіювати ваші файли до нової гілки і після цього видалити стару гілку, щоб не втратити дані.

2023-09-12 05:34 UTC, TetianaShevch commented
Добрий день, Марино!

Зараз в дорозі, як тільки приїду на роботу, буду виправляти.

Тетяна

вт, 12 вер. 2023, 07:16 користувач Maryna Kondratiuk <
***@***.***> пише:

> ***@***.**** requested changes on this pull request.
>
> Добрий ранок Тетяно! Ви клонувались від неправильної гілки, ви зробили
> клон він main, а потрібно було клонуватись від dev. Тепер коли ви зробили
> пул реквест, виник конфлікт, ваш файл main хоче замінти мій файл main. Щоб
> корректно залити ваші файли в правильну папку я рекомендую вам зробити іще
> одну гілку, тільки клонуватися від dev гілки, потім скопіювати ваші файли
> до нової гілки і після цього видалити стару гілку, щоб не втратити дані.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/djmary-k/App_assistant/pull/6#pullrequestreview-1621199461>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BBE6IHXPAMPO4IU4X2XZMQ3XZ7OYPANCNFSM6AAAAAA4T32Y6I>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2023-09-12 07:51 UTC, closed without merging